substitutions:
  _REGION: asia-southeast1
  _ARTIFACT_REPO: backend
  _API_SERVICE: detective-quill-api
  _WORKER_SERVICE: detective-quill-worker
  _GATEWAY_SERVICE: detective-quill-gateway

steps:
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - -t
      - $_REGION-docker.pkg.dev/detective-quill/$_ARTIFACT_REPO/backend:$COMMIT_SHA
      - -t
      - $_REGION-docker.pkg.dev/detective-quill/$_ARTIFACT_REPO/backend:latest
      - -f
      - apps/backend/Dockerfile
      - .

  - name: gcr.io/cloud-builders/docker
    id: push
    waitFor: [build]
    args:
      - push
      - --all-tags
      - $_REGION-docker.pkg.dev/detective-quill/$_ARTIFACT_REPO/backend

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy-api
    waitFor: [push]
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_API_SERVICE
      - --image=$_REGION-docker.pkg.dev/detective-quill/$_ARTIFACT_REPO/backend:$COMMIT_SHA
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --port=3001

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy-worker
    waitFor: [push]
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_WORKER_SERVICE
      - --image=$_REGION-docker.pkg.dev/detective-quill/$_ARTIFACT_REPO/backend:$COMMIT_SHA
      - --region=$_REGION
      - --platform=managed
      - --no-allow-unauthenticated
      - --port=3002
      - --command=node
      - --args=dist/worker/worker.main

  - name: gcr.io/cloud-builders/docker
    id: build-nginx
    args:
      - build
      - -t
      - $_REGION-docker.pkg.dev/detective-quill/$_ARTIFACT_REPO/nginx:$COMMIT_SHA
      - -t
      - $_REGION-docker.pkg.dev/detective-quill/$_ARTIFACT_REPO/nginx:latest
      - -f
      - apps/nginx/Dockerfile
      - apps/nginx

  - name: gcr.io/cloud-builders/docker
    id: push-nginx
    waitFor: [build-nginx]
    args:
      - push
      - --all-tags
      - $_REGION-docker.pkg.dev/detective-quill/$_ARTIFACT_REPO/nginx

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy-gateway
    waitFor: [push-nginx]
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_GATEWAY_SERVICE
      - --image=$_REGION-docker.pkg.dev/detective-quill/$_ARTIFACT_REPO/nginx:$COMMIT_SHA
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080

images:
  - $_REGION-docker.pkg.dev/detective-quill/$_ARTIFACT_REPO/backend:$COMMIT_SHA
  - $_REGION-docker.pkg.dev/detective-quill/$_ARTIFACT_REPO/backend:latest
  - $_REGION-docker.pkg.dev/detective-quill/$_ARTIFACT_REPO/nginx:$COMMIT_SHA
  - $_REGION-docker.pkg.dev/detective-quill/$_ARTIFACT_REPO/nginx:latest

options:
  logging: CLOUD_LOGGING_ONLY
