events {
  worker_connections 1024;
}

http {
  upstream backend {
    server detective-quill-api-7l6jd5wida-as.a.run.app;
  }

  upstream query_engine {
    server query-engine-7l6jd5wida-as.a.run.app;
  }

  server {
    listen 8080;

    location /api/ {
      proxy_pass https://backend/;
      proxy_ssl_verify off;
      proxy_set_header Host $proxy_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /query/ {
      proxy_pass https://query_engine/;
      proxy_ssl_verify off;
      proxy_set_header Host $proxy_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
      proxy_pass https://backend/;
      proxy_ssl_verify off;
      proxy_set_header Host $proxy_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
